# name: deploy to ec2
# on:
#     push:
#       branches:
#         - master
# jobs:

#     deploy:
#         runs-on: ubuntu-latest

#         steps:

#             - name: checkout code
#               uses: actions/checkout@v3

#             - name: Terraform Script
#               uses: hashicorp/setup-terraform@v3
#               with:
#                 terraform_version: 1.6.3

